version: '1.0'

nameservers:
  production:
    host: localhost
    ns_port: 9090
    broadcast: false
    ns_bchost: null
    ns_bcport: 9091
    ns_autoclean: 0.0
    storage: memory

daemons:
  lockable:
    module: pyrolab.server
    classname: LockableDaemon
    host: localhost
    port: 0
    unixsocket: null
    nathost: null
    natport: 0
    servertype: thread
    nameservers:
    - production

services:
  library:
    module: libservice
    classname: LibraryCatalog
    description: Library catalog system
    instancemode: single
    daemon: lockable
    nameservers:
    - production

autolaunch:
  nameservers:
  - production
  daemons:
  - lockable
