# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

from datetime import datetime

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'PyroLab'
copyright = f"2020-{datetime.now().year}, Sequoia Ploeg"
author = 'Sequoia Ploeg'

# The full version, including alpha/beta/rc tags
release = '0.2.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'numpydoc',
    # "sphinx.ext.intersphinx",
    # "sphinx.ext.coverage",
    # "sphinx.ext.doctest",
    'sphinx.ext.autosummary',
    # 'sphinx_autodoc_typehints',
    # "sphinx.ext.graphviz",
    # "sphinx.ext.ifconfig",
    # 'matplotlib.sphinxext.plot_directive',
    # 'IPython.sphinxext.ipython_console_highlighting',
    # 'IPython.sphinxext.ipython_directive',
    # "sphinx.ext.imgmath",
    # 'sphinx.ext.todo', #
    'sphinx.ext.mathjax',
    # 'sphinx.ext.viewcode', #
    # 'sphinx.ext.githubpages', #
    # 'sphinx_autodoc_typehints', #
    'sphinx_panels',
]

autosummary_generate = True  # Turn on sphinx.ext.autosummary
# autosummary_generate = True if include_api else ["index"]
autodoc_typehints = "none"
autoclass_content = "class"  # Add __init__ doc (ie. params) to class summaries
# html_show_sourcelink = False  # Remove 'view source code' from top of page (for html, not python)
autodoc_inherit_docstrings = True  # If no docstring, inherit from base class
# add_module_names = False # Remove namespaces from class/method signatures

autodoc_mock_imports = [
    'numpy',
    'scipy',
    'Pyro5',
    'pydantic',
    'yaml',
    'appdirs',
    'deprecation',
    'appnope',
    'typer',
    'colorama',
    'tabulate', 
    'serial',
    'thorlabs_kinesis',
    'pyfirmata',
    'sacher_tec',
    'firmata',
]

panels_add_bootstrap_css = False

# numpydoc
numpydoc_attributes_as_param_list = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'pydata_sphinx_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_theme_options = {
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/BYUCamachoLab/pyrolab",
            "icon": "fab fa-github-square",
        },
        # {
        #     "name": "GitLab",
        #     "url": "https://gitlab.com/<your-org>/<your-repo>",
        #     "icon": "fab fa-gitlab",
        # },
        # {
        #     "name": "Twitter",
        #     "url": "https://twitter.com/<your-handle>",
        #     "icon": "fab fa-twitter-square",
        # },
    ],
    "navigation_with_keys": False,
}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = ["themes"]

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = "_static/img/logo.svg"

# You can remove the sidebar from some pages by listing them here
# html_sidebars = {
#   "pagename": []
# }

html_css_files = [
    "css/getting_started.css",
    "css/pyrolab.css",
]

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = "_static/img/favicon.ico"

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
